MediaLibrary.Web/Models/MediaModel.cs
using MediaLibrary.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MediaLibrary.Web.Models
{
    public class MediaModel
    {
        public MediaTO Media { get; set; }
    }
}

MediaLibrary.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MediaLibrary.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        // GET: Contact
        public ActionResult Contact()
        {
            return View();
        }

        // GET: About
        public ActionResult About()
        {
            return View();
        }

    }
}

MediaLibrary.Web/Controllers/MediaController.cs
using MediaLibrary.Common;
using MediaLibrary.DAL;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MediaLibrary.Web.Controllers
{
    public class MediaController : Controller
    {
        private MediaRepo mediaRepo { get; set; }
        public MediaController()
        {
            mediaRepo = new MediaRepo(new MediaLibraryContext());
        }

        // GET: Media
        public ActionResult Index()
        {
            var medias = mediaRepo.GetAllMedias();
            return View(medias);
        }

        // GET: Media/Details/5
        public ActionResult Details(int id)
        {
            var media = mediaRepo.GetById(id);
            return View(media);
        }

        // GET: Media/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Media/Create
        [HttpPost]
        public ActionResult Create(MediaTO media)
        {
            try
            {
                mediaRepo.CreateMedia(media);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Media/Edit/5
        public ActionResult Edit(int id)
        {
            var mediaToEdit = mediaRepo.GetById(id);
            return View(mediaToEdit);
        }

        // POST: Media/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, MediaTO media)
        {
            try
            {
                var temp = mediaRepo.ModifyMedia(media);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Media/Delete/5
        public ActionResult Delete(int id)
        {
            var mediToDelete = mediaRepo.GetById(id);
            return View(mediToDelete);
        }

        // POST: Media/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, MediaTO media)
        {
            try
            {
                mediaRepo.DeleteMedia(media);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MediaLibrary.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="jumbotron p-4 mt-5 jumbotron-trans">
    <h1>About</h1>
    <div>This project is made only for learning purpose. I am currently in a .Net training to beacome a .Net developer. 
    I had one week to learn and create an entire .net web application using ASP.Net MVC 5. Here is the result </div>
</div>

MediaLibrary.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="jumbotron p-4 mt-5 jumbotron-trans">
    <h1>Contact</h1>
    <h4>Hello world!</h4>
    <div>Hi folks ! I am Orlane, a young women who just dive into development those past few months.</div>
    <div>This is my first web application persormed with MVC5. I really enjoyed creating it, I hope you'll enjoy to browse it too.  </div>
    <div>Do not hesitate to contact me or just check my other projects on GitHub <a target="blank" href="https://github.com/Orl4ne">Orl4ne</a> </div>
</div>

MediaLibrary.Web/Views/Home/Index.cshtml
    <div class="h-100 align-items-center mx-center">
        <div class="mx-center">
            <strong>@Html.ActionLink("Go to the Library","Index", "Media", new object { }, new {@class="btn btn-warning btn-lg center-screen"})</strong>
        </div>
    </div>

MediaLibrary.Web/Views/Media/Create.cshtml
@model MediaLibrary.Common.MediaTO

@{
    ViewBag.Title = "Create";
}
    <div class="jumbotron p-4 mt-5 jumbotron-trans">
        <h1>Create a new media</h1>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Path, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-warning" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
        </div>

MediaLibrary.Web/Views/Media/Delete.cshtml
@model MediaLibrary.Common.MediaTO

@{
    ViewBag.Title = "Delete";
}
<div class="jumbotron p-4 mt-5 jumbotron-trans">
    <h1>Delete a media</h1>
    @*<h3>Are you sure you want to delete this?</h3>*@
    <div>
        <hr />
            <h4 class=" mb-0 font-weight-bolder">
                @Html.DisplayNameFor(model => model.Name)
            </h4>

            <div class="mt-0 mb-3">
                @Html.DisplayFor(model => model.Name)
            </div>

            <h4 class=" mb-0 font-weight-bolder">
                @Html.DisplayNameFor(model => model.Path)
            </h4>

            <div class="mt-0 mb-3">
                @Html.DisplayFor(model => model.Path)
            </div>

            <h4 class=" mb-0 font-weight-bolder">
                @Html.DisplayNameFor(model => model.Type)
            </h4>

            <div class="mt-0 mb-3">
                @Html.DisplayFor(model => model.Type)
            </div>


       
            <div class="form-actions no-color">
                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#DeletingPopUp">Delete</button>|
                @Html.ActionLink("Back to List", "Index")
            </div>
    </div>
</div>

<div class="modal" id="DeletingPopUp">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Deleting</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure that you want to delete this media ?</p>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-warning" />
                    </div>
                }
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

MediaLibrary.Web/Views/Media/Details.cshtml
@model MediaLibrary.Common.MediaTO

@{
    ViewBag.Title = "Details";
}
<div class="jumbotron p-4 mt-5 jumbotron-trans">
    <h1>Details</h1>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Path)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Path)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

MediaLibrary.Web/Views/Media/Edit.cshtml
@model MediaLibrary.Common.MediaTO

@{
    ViewBag.Title = "Edit";
}
<div class="jumbotron p-4 mt-5 jumbotron-trans">
    <h1>Editing the media</h1>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Path, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-warning" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

MediaLibrary.Web/Views/Media/Index.cshtml
@model IEnumerable<MediaLibrary.Common.MediaTO>

@{
    ViewBag.Title = "My Medias";
}
<div class="jumbotron p-4 mt-5 jumbotron-trans">
    <h1>Library</h1>
    @Html.ActionLink("Create New Media", "Create", new object { },
new { @class = "btn btn-warning " })
    <div class="float-right">
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" id="myInput">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
        </form>

    </div>

    <table class="table" id="myTable">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Path)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>

@section Scripts{
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
}

MediaLibrary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Orl4ne ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <style>
        body {
            color: black;
            background-color: white;
            background-image: url(/Content/images/Library-image.jpg);
        }
    </style>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-fixed-top">
        @*<a class="navbar-brand" href="#">My Media Application</a>*@
        <a>@Html.ActionLink("My Media Library", "Index", "Home", new object { }, new { @class = "text-light navbar-brand" })</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Library", "Index", "Media", new object { }, new { @class = "text-light" })</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home", new object { }, new { @class = "text-light" })</li>
                <li>@Html.ActionLink("About", "About", "Home", new object { }, new { @class = "text-light" })</li>
            </ul>
        </div>
    </nav>
    
    <main class="h-100 container body-content">
        @RenderBody()
    </main>

    <footer class="container bg-primary text-light fixed-bottom">
        &copy; @DateTime.Now.Year - Orl4ne ASP.NET Application
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>